@host = 127.0.0.1:5000
@contentType = application/json

GET http://{{host}}/Get/KBank
###

POST http://{{host}}/Get/KBank
content-type: {{contentType}}

{
  "username": "gotgot7",
  "password": "gotgat77"
}
###