@host = 127.0.0.1:5000
@contentType = application/json


POST http://{{host}}/KBank
content-type: {{contentType}}

{
  "username": "gotgot7",
  "password": "gotgat77"
}

###

POST http://{{host}}/BAY
content-type: {{contentType}}

{
  "username": "jipjip39",
  "password": "jopjop38"
}

###